version:                   '3.3'

services:
  app:
    container_name: docker-chanter-grp2
    build: .
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL:  ${EMAIL}
    restart: always
    depends_on:
    - mongo-grp2

  mongo-grp2:
    container_name: mongo-grp2
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

networks:
  default:
    external:
      name: ${NETWORK}
